name: mobidata_bw_flutter
description: A minimal Flutter to browse MobiData BW data on a map.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  dio: ^5.7.0
  geolocator: ^13.0.1
  flutter_spinkit: ^5.2.1
  hive: ^2.0.0          # todo: switch local db
  hive_flutter: ^1.0.0
  path_provider: ^2.0.0
  gtfs_realtime_bindings: ^1.1.0
  path: ^1.9.0
  sqlite3: ^2.4.0
  proj4dart: ^2.1.0
  simplify: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
