name: mobidata_bw_flutterer
description: A minimal Flutter to browse MobiData BW parking data on a map (Android-first).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  dio: ^5.7.0
  geolocator: ^13.0.1
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
